#' Import an Agilent MassHunter chromatogram from a csv file into a useful
#' format
#'
#' This function takes a csv file that was generated by exporting chromatograms
#' from Agilent MassHunter Qualitative Analysis and tidies the data into a
#' useful data.frame since the output from Agilent software is so weird. Input
#' is a character string that is the name of the csv file.
#'
#'
#' @param csvfile A character string that is the csv filename that was exported
#'   from MassHunter Qual.
#'
#' @return Output is a tidy data.frame with column indicating the file, the
#'   chromatogram type, the ionization mode, the retention time, the counts,
#'   etc.
#' @export
#'
#'
#'
importChrom <- function(csvfile){

      # Defining the pipe operator
      `%>%` <- magrittr::`%>%`

      # MassHunter puts the file name on the 1st line but only
      # in one cell, and this causes R to interpret the file as
      # having only 1 column. Thus the odd way of reading
      # in the file.
      DF1 <- scan(csvfile, nlines = 1, what = "character", sep = "|")
      DF <- read.csv(csvfile, stringsAsFactors = FALSE,
                     skip = 1)
      names(DF) <- c("Point", "Time_min", "Count")
      DF$Point[DF$Point == "#Point"] <- "Point"

      InjNameRows <- which( stringr::str_detect(DF$Point, "\\#"))
      DF$Chromatogram <- NA

      for(i in 2:length(InjNameRows)){
            DF$Chromatogram[InjNameRows[i-1]:InjNameRows[i]] <-
                  DF$Point[InjNameRows[i-1]]
            if(i == length(InjNameRows)){
                  DF$Chromatogram[InjNameRows[i]:nrow(DF)] <-
                        DF$Point[InjNameRows[i]]
            }
      }

      # Taking care of the special case of 1st chromatogram
      DF$Chromatogram[1:(InjNameRows[1]-1)] <- DF1
      InjNameRows <- c(1, InjNameRows)

      AllInjections <- stringr::str_trim(DF[InjNameRows, "Chromatogram"])
      # If there were any injections where there was "ZERO ABUNDANCE", that adds
      # a bunch of spaces after the .d. Removing those.
      AllInjections <- sub("    ...ZERO ABUNDANCE...", "", AllInjections)
      Injections <- as.data.frame(stringr::str_split(AllInjections, " ",
                                                     simplify = TRUE))

      # At least so far, when I import MRM chromatograms, the spaces work out to
      # a data.frame with 9 columns and, for SIM chromatograms, 4 columns.
      if(ncol(Injections) > 4){                       # MRM experiments
            # MRM
            Injections <- dplyr::mutate(
                  Injections, Chromatogram = AllInjections,
                  Mode = sub("\\#", "", V1),
                  ChromatogramType = stringr::str_extract(V2, "^[A-Z]{3}"),
                  Ion = ifelse(ChromatogramType == "SIM",
                               stringr::str_extract(V2, "[0-9]{2,4}\\.[0-9]{1,}"),
                               gsub("\\(|\\)", "", paste(V5, V6, V7))),
                  Ion = ifelse(ChromatogramType == "TIC", "all", Ion),
                  ChromatogramType = ifelse(stringr::str_detect(Mode, "BinPump"),
                                            "binpump pressure", ChromatogramType),
                  PrecursorIon = as.numeric(stringr::str_extract(V5, "[0-9]{2,4}\\.[0-9]{1,}")),
                  ProductIon = as.numeric(stringr::str_extract(V7, "[0-9]{2,4}\\.[0-9]{1,}")),
                  File = V8) # Will need to adjust this with files that have spaces!

            Injections$File[Injections$ChromatogramType == "TIC"] <-
                  Injections$V9[Injections$ChromatogramType == "TIC"]
            Injections$File[Injections$ChromatogramType == "binpump pressure"] <-
                  Injections$V5[Injections$ChromatogramType == "binpump pressure"]

      } else {                         # SIM experiments
            # SIM
            Injections <-  dplyr::mutate(
                  Injections, Chromatogram = AllInjections,
                  Mode = sub("\\#", "", V1),
                  ChromatogramType = stringr::str_extract(V2, "^[A-Z]{3}"),
                  Ion = as.numeric(stringr::str_extract(V2, "[0-9]{2,4}\\.[0-9]{1,}")),
                  # If there were only SIM files, then File exists only
                  # in column V4.
                  File = V4,
                  ChromatogramType = ifelse(Mode == "BinPump1",
                                            "binpump pressure", ChromatogramType))
      }

      Injections <- Injections %>% dplyr::select(-matches("^V"))

      DF <- suppressWarnings(
            DF %>% dplyr::mutate(Chromatogram = stringr::str_trim(Chromatogram),
                                 Chromatogram = sub("    ...ZERO ABUNDANCE...", "",
                                                    Chromatogram)) %>%
                  dplyr::left_join(Injections, by = "Chromatogram") %>%
                  dplyr::mutate_at(.vars = dplyr::vars(matches("Point|Time_min|Count")),
                                   .funs = as.numeric) %>%
                  dplyr::filter(complete.cases(Time_min))
      )

      return(DF)


}



