#' Import an Agilent MassHunter chromatogram from a csv file into a useful
#' format
#'
#' This function takes a csv file that was generated by exporting TIC, SIM, MRM,
#' or binary-pump pressure chromatograms from Agilent MassHunter Qualitative
#' Analysis and tidies the data into a useful data.frame since the output from
#' Agilent software is so weird. Input is a character string that is the name of
#' the csv file. This does assume that the chromatogram file includes either SIM
#' \emph{or} MRM experiments but not both.
#'
#'
#' @param csvfile The csv file name that was exported from MassHunter Qual
#'
#' @return Output is a tidy data.frame with column indicating the file, the
#'   chromatogram type, the ionization mode, the retention time, the counts,
#'   etc.
#' @export
#'
#'
#'
importChrom <- function(csvfile){

      # Defining the pipe operator
      `%>%` <- magrittr::`%>%`

      # MassHunter puts the file name on the 1st line but only
      # in one cell, and this causes R to interpret the file as
      # having only 1 column. Thus the odd way of reading
      # in the file.
      DF1 <- scan(csvfile, nlines = 1, what = "character", sep = "|")
      # Sometimes getting extra commas at end of this. Removing.
      DF1 <- gsub(",", "", DF1)
      DF <- read.csv(csvfile, stringsAsFactors = FALSE,
                     skip = 1)
      names(DF) <- c("Point", "Time_min", "Count")
      DF$Point[DF$Point == "#Point"] <- "Point"

      InjNameRows <- which( stringr::str_detect(DF$Point, "\\#"))
      DF$Chromatogram <- NA

      for(i in 2:length(InjNameRows)){
            DF$Chromatogram[InjNameRows[i-1]:InjNameRows[i]] <-
                  DF$Point[InjNameRows[i-1]]
            if(i == length(InjNameRows)){
                  DF$Chromatogram[InjNameRows[i]:nrow(DF)] <-
                        DF$Point[InjNameRows[i]]
            }
      }

      # Taking care of the special case of 1st chromatogram
      DF$Chromatogram[1:(InjNameRows[1]-1)] <- DF1
      InjNameRows <- c(1, InjNameRows)

      # Sometimes, I think only w/SIM experiments, there are quotes around
      # Chromatogram. Removing those.
      DF$Chromatogram <- gsub("\"", "", DF$Chromatogram)


      AllInjections <- stringr::str_trim(DF[InjNameRows, "Chromatogram"])
      # If there were any injections where there was "ZERO ABUNDANCE", that adds
      # a bunch of spaces after the .d. Removing those.
      AllInjections <- sub("    ...ZERO ABUNDANCE...", "", AllInjections)
      Injections <- as.data.frame(stringr::str_split(AllInjections, " ",
                                                     simplify = TRUE))


      ## Dealing with spaces and quotes in the file name columns
      concat <- function(x){
            gsub("\"", "",
                 stringr::str_trim(stringr::str_c(x, collapse = " "))
            )
      }

      # MRM experiments
      if(any(stringr::str_detect(Injections$V2, "MRM"))){
            # When the type was TIC, 1st column with file is V9
            # When MRM, 1st column w/file is V8
            # When SIM, 1st column w/file is XXXXXXXXXXXXXX
            # When BinPump, 1st column w/file is V5
            # For all of these, all the remaining columns are only pieces of the file names.
            TIC <- Injections[stringr::str_detect(Injections$V2, "TIC"), ]
            TIC$V9 <- apply(TIC[, 9:ncol(TIC)], MARGIN = 1, FUN = concat)
            TIC <- TIC[, 1:9]

            MRM <- Injections[stringr::str_detect(Injections$V2, "MRM"), ]
            MRM$V8 <- apply(MRM[, 8:ncol(MRM)], MARGIN = 1, FUN = concat)
            MRM <- MRM[, 1:8]

            BinP <- Injections[stringr::str_detect(Injections$V1, "BinPump"), ]
            BinP$V5 <- apply(BinP[, 5:ncol(BinP)], MARGIN = 1, FUN = concat)
            BinP <- BinP[, 1:5]

            Injections <- dplyr::bind_rows(TIC, MRM, BinP)

      } else { # SIM experiments
            # When the type was TIC, 1st column with file is V9
            # When MRM, 1st column w/file is V8
            # When SIM, 1st column w/file is XXXXXXXXXXXXXX
            # When BinPump, 1st column w/file is V5
            # For all of these, all the remaining columns are only pieces of the file names.
            TIC <- Injections[stringr::str_detect(Injections$V2, "TIC"), ]
            TIC$V4 <- apply(TIC[, 4:ncol(TIC)], MARGIN = 1, FUN = concat)
            TIC <- TIC[, 1:4]

            SIM <- Injections[stringr::str_detect(Injections$V2, "EIC"), ]
            SIM$V4 <- apply(SIM[, 4:ncol(SIM)], MARGIN = 1, FUN = concat)
            SIM <- SIM[, 1:4]

            BinP <- Injections[stringr::str_detect(Injections$V1, "BinPump"), ]
            BinP$V4 <- apply(BinP[, 4:ncol(BinP)], MARGIN = 1, FUN = concat)
            BinP <- BinP[, 1:4]

            Injections <- dplyr::bind_rows(TIC, SIM, BinP)
      }


      # With MRM chromatograms, the spaces work out to a data.frame with 9
      # columns and, with SIM chromatograms, 4 columns.
      if(any(stringr::str_detect(Injections$V2, "MRM"))){         # MRM experiments
            # MRM
            Injections <- dplyr::mutate(
                  Injections, Chromatogram = AllInjections,
                  Mode = sub("\\#", "", V1),
                  ChromatogramType = stringr::str_extract(V2, "^[A-Z]{3}"),
                  Ion = ifelse(ChromatogramType == "SIM",
                               stringr::str_extract(V2, "[0-9]{2,4}\\.[0-9]{1,}"),
                               gsub("\\(|\\)", "", paste(V5, V6, V7))),
                  Ion = ifelse(ChromatogramType == "TIC", "all", Ion),
                  ChromatogramType = ifelse(stringr::str_detect(Mode, "BinPump"),
                                            "binpump pressure", ChromatogramType),
                  PrecursorIon = as.numeric(stringr::str_extract(V5, "[0-9]{2,4}\\.[0-9]{1,}")),
                  ProductIon = as.numeric(stringr::str_extract(V7, "[0-9]{2,4}\\.[0-9]{1,}")),
                  File = V8) # Will need to adjust this with files that have spaces!

            Injections$File[Injections$ChromatogramType == "TIC"] <-
                  Injections$V9[Injections$ChromatogramType == "TIC"]
            Injections$File[Injections$ChromatogramType == "binpump pressure"] <-
                  Injections$V5[Injections$ChromatogramType == "binpump pressure"]

      } else {                         # SIM experiments
            # SIM
            Injections <-  dplyr::mutate(
                  Injections, Chromatogram = AllInjections,
                  Mode = sub("\\#", "", V1),
                  ChromatogramType = stringr::str_extract(V2, "^[A-Z]{3}"),
                  Ion = as.numeric(stringr::str_extract(V2, "[0-9]{2,4}\\.[0-9]{1,}")),
                  # If there were only SIM files, then File exists only
                  # in column V4.
                  File = V4,
                  ChromatogramType = ifelse(Mode == "BinPump1",
                                            "binpump pressure", ChromatogramType))
      }

      Injections <- Injections %>% dplyr::select(-matches("^V"))

      DF <- suppressWarnings(
            DF %>% dplyr::mutate(Chromatogram = stringr::str_trim(Chromatogram),
                                 Chromatogram = sub("    ...ZERO ABUNDANCE...", "",
                                                    Chromatogram)) %>%
                  dplyr::left_join(Injections, by = "Chromatogram") %>%
                  dplyr::mutate_at(.vars = dplyr::vars(matches("Point|Time_min|Count")),
                                   .funs = as.numeric) %>%
                  dplyr::filter(complete.cases(Time_min))
      )

      return(DF)


}



